### ISSUE TITLE
Pre-unconf meet-up

### ISSUE THREAD

**Issue by jeroen** [ropensci/unconf#15]
Anyone in the area wants to meet up for coffee or a drink? If you're not in the area and just want an excuse to get away from the snow for a bit, that's cool too.

**Comment by karthik** [comment]
We'll definitely do something informal (dinner and drinks) on Wednesday night.  But I'm also up for getting something more informal together sooner. :stars:

**Comment by timphan** [comment]
I seem to remember some Tweets from #user2014 about karaoke...hint hint

**Comment by sjackman** [comment]
I'd like to meet up on Wednesday night.

**Comment by karthik** [comment]
Great. I'll try to find a place large enough to accommodate a big group. Jenny, Carl, Scott, Rich and I have an internal meeting in Berkeley earlier so we'll head up after that is done.

**Comment by hadley** [comment]
I'm going to be free on Monday afternoon if anyone wants to hang out

**Comment by karthik** [comment]
I'm down. I think Jeroen will be around too. I can find us a good spot once we know how many. :cocktail:

**Comment by jeroen** [comment]
This Monday or in the week of the conf? I'm at the east coast all of next week :(

**Comment by karthik** [comment]
Hadley meant week of conf.

**Comment by karthik** [comment]
@jeroenooms We've got a plan for Monday. If anyone else is around and wants to join us, please ping me directly.

**Comment by karthik** [comment]
If anyone is interested in meeting up for dinner on Wednesday night (say 7pm), please RSVP in this thread. I'll find us a spot.

**Comment by srvanderplas** [comment]
I arrive about 7, but would be interested assuming my flight is on time.

**Comment by karthik** [comment]
I'll just suggest a spot. Let's do dinner at Zero Zero. Meeting there around 7:30

http://www.zerozerosf.com/
826 Folsom St

They can generally accommodate groups of variable sizes.

**Comment by sjackman** [comment]
I'm in for dinner. See you there.

**Comment by dgrtwo** [comment]
I'll be there for dinner!

(Perhaps the plans should be mentioned on the logistics page or elsewhere?)

**Comment by karthik** [comment]
I currently have a reservation for two tables (~ 5 each) although they will try to fit us into one big table. It's an unusually busy conference week in SF but we'll make it work. 

@dgrtwo for this particular one lets just have people rsvp here. 

And Jillian I have you in this count.

**Comment by jeroen** [comment]
Count me in as well

**Comment by timphan** [comment]
I don't think I'll make it to SF in time by 7:30 , but let me know if you'll be doing any after-dinner activities. Have a fun one!

**Comment by karthik** [comment]
@timphan Just keep an eye on this thread. I'm unlikely to stay out late tomorrow night but others might. Also jump in on our Slack #35 for easier contact with people while they are out.

**Comment by mine-cetinkaya-rundel** [comment]
I should be in SF by then, I'll plan on joining if there's room in the reservation

**Comment by karthik** [comment]
Please do, we'll make it work.

**Comment by jordansread** [comment]
I'm in the same boat for a later arrival (~8:30 if all goes well). Would like to join in if there is room too.

**Comment by stephaniehicks** [comment]
Oh I missed this thread somehow. Is there still room to join in?

**Comment by karthik** [comment]
I might move the venue. Anyone opposed to western african food?
http://www.bissapbaobab.com/

It's hard to get a table for a party this big but this place can host us.

**Comment by sjackman** [comment]
I'm okay with wherever. I may or may not have access to data in the states, depending on the whim of the mobile gods. Please send me a text if the venue changes.

**Comment by stephaniehicks** [comment]
Works for me, but I also realize I didn't RSVP ahead. So I don't want to cause too much trouble.

**Comment by ramnathv** [comment]
I wish I could join, but it is the cricket world cup semi-finals today :smile:

**Comment by jeroen** [comment]
FYI -- Uber is running a promo for Uber Pool in SF: $7 to get anywhere in SF, and $15 from/to the airport. That's almost the same price as the BART, and probably much easier.

**Comment by karthik** [comment]
Updated. We're going here:

3372 19th Street
San Francisco, CA 94110 
Cross Street: 19 th Street 

Susan: I'll call you in case you don't see this.

**Comment by srvanderplas** [comment]
Looks like I can get off of BART near there, so should be about as late as
I would have been before.

**Comment by sjackman** [comment]
Great. I'll see you at Bissap Baobab at 7:30 tonight.
