### ISSUE TITLE
turf.js

### ISSUE THREAD

**Issue by sckott** [ropensci/unconf#22]
I'm very interested in working on an R client wrapping [turf.js](http://turfjs.org/) - related to #2 - we can wrap with `V8`  

maybe there are other js libraries to join this effort

**Comment by lmullen** [comment]
I'd be very interested in working on turf.js/[lawn](https://github.com/sckott/lawn). I think this package could help bring interactive mapping packages like leafletr and cartographer to the next level by letting them incorporate more analysis and not just plotting.

**Comment by sckott** [comment]
Cool, cool. It is started, but we're not very far yet, so we can work on more at the event

**Comment by hadley** [comment]
Rather than wrapping with V8, I really think it would be worthwhile to learn some Rcpp + C++ and reimplement from scratch. It would be slower progress at first, but you'd end with a much better final product.

**Comment by lmullen** [comment]
I was wondering whether this would be worthwhile to do in C++. I've been trying to port the [simple-statistics](http://www.macwright.org/2013/02/18/literate-jenks.html) implementation of Jenks breaks (which is what [turf.js uses](https://github.com/Turfjs/turf-jenks/blob/master/index.js#L78)) to C++ as an excuse to give it a try.

**Comment by jeroen** [comment]
@hadley I understand if you want to avoid the V8 dependency, but I highly doubt that you are going to end up with "a much better final product" by "learning some C++" and hacking together a reimplementation. The turf.js library seems like a very complete, properly tested, well-maintained library with many users. It might be a fun project to try and re-implement the algorithms in R or C++, but I doubt it will be "better".
